FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y apache2 php git unzip && \
    apt-get clean

RUN rm -rf /var/www/html/* && \
    git clone https://github.com/blueimp/Gallery.git /var/www/html/

RUN chown -R www-data:www-data /var/www/html

EXPOSE 80

CMD ["apachectl", "-D", "FOREGROUND"]
